'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProjectAddition

    '''<summary>
    '''cboBusinessUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboBusinessUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboDIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDIC As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtProjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProjectName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboProjectLeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboProjectLeader As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDepartment As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboExpenseHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboExpenseHead As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cboFinanceLeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboFinanceLeader As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCategory As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''plcapex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plcapex As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''cboTeamMembers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTeamMembers As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cboDosage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDosage As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cboMfgCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMfgCode As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cboTherapy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTherapy As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cboPackcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPackcode As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cboManfCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboManfCode As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cboProjectStartMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboProjectStartMonth As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboProjectStartYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboProjectStartYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRecoverableLosses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecoverableLosses As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProbability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProbability As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CalculateTDC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalculateTDC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtProbabilityAdjustedAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProbabilityAdjustedAmt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboSavingsStartMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSavingsStartMonth As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboSavingsStartYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSavingsStartYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtOneOffRecoverable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOneOffRecoverable As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AccountingMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccountingMonth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTimeAdjustedAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTimeAdjustedAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboTenureEndMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTenureEndMonth As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboTenureEndYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTenureEndYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkCommitted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCommitted As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''AccountingYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccountingYear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotalAdjustedAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalAdjustedAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Textbox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Dropdownlist3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Textbox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Textbox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Dropdownlist1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Textbox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Textbox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Dropdownlist2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Textbox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Textbox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Dropdownlist4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Textbox8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Textbox9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Dropdownlist5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Textbox10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Textbox11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Dropdownlist6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist6 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Textbox12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Textbox13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Dropdownlist7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist7 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Textbox14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Textbox15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Dropdownlist8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist8 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Textbox16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox16 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCostAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCostAmt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Dropdownlist9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dropdownlist9 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Textbox18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textbox18 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SaveProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveProject As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cancel As Global.System.Web.UI.WebControls.Button
End Class
