'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProjectAddition

    '''<summary>
    '''cboBusinessUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboBusinessUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCategory As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtProjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProjectName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProjectSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProjectSummary As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboProjectLeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboProjectLeader As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDepartment As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboExpenseHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboExpenseHead As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboFinanceLeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboFinanceLeader As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboProjectClassification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboProjectClassification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboDIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDIC As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''plcapex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plcapex As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''cboTeamMembers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTeamMembers As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cboDosage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDosage As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cboMfgCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMfgCode As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cboTherapy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTherapy As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cboPackcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPackcode As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cboBulkCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboBulkCode As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cboProjectStartMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboProjectStartMonth As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboProjectStartYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboProjectStartYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboProjectEndMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboProjectEndMonth As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboProjectEndYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboProjectEndYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAnnualSavings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnnualSavings As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboProbability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboProbability As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CalculateTDC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalculateTDC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtProbabilityAdjustedAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProbabilityAdjustedAmt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboSavingsStartMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSavingsStartMonth As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboSavingsStartYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSavingsStartYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtOneOffSaving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOneOffSaving As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAccountingMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountingMonth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTimeAdjustedAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTimeAdjustedAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboSavingsEndMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSavingsEndMonth As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboSavingsEndYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSavingsEndYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtStage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStage As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkCommitted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCommitted As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtAccountingYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountingYear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotalAdjustedAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalAdjustedAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCapexCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCapexCost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboCapexCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCapexCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCapexJust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCapexJust As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtWorkCapCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWorkCapCost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboWorkCapCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboWorkCapCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtWorkCapJust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWorkCapJust As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRegulatoryCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegulatoryCost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboRegulatoryCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboRegulatoryCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRegulatoryJust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegulatoryJust As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSampleCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSampleCost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboSampleCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSampleCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSampleJust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSampleJust As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRDCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRDCost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboRDCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboRDCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRDJust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRDJust As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQACost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQACost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboQACurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboQACurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtQAJust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQAJust As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAuditCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAuditCost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboAuditCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAuditCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAuditJust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAuditJust As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOtherCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherCost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboOtherCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboOtherCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtOtherJust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherJust As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotalCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalCost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboTotalCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTotalCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTotalJust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalJust As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SaveProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveProject As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TestOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestOut As Global.System.Web.UI.WebControls.TextBox
End Class
